# fly.toml app configuration file generated for meidev-emailsender on 2023-05-31T09:11:57+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "meidev-emailsender"
primary_region = "lhr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
